sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t blakenan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true blakenan/docker-react npm run test